### ISSUE TITLE
Linux/Mac support

### ISSUE THREAD

**Issue by psamim** [DazEdword/AKClipper#17]
Hi,

Is this tool available on Linux?

Considering the availability of dot-net for Linux, I think it can run on Linux. 
Can you proved building instructions?

Thanks

**Comment by DazEdword** [comment]
Heya,

You are right, .NET is available for Linux and Mac too, and since the core API is written in the .NET Standard libraries it should be compatible out of the box. However, the Windows application's GUI is WPF, which (as far as I know) has no Linux support. Anyway, I'm at the moment working on the web implementation (using the same library mentioned above plus ASP.NET Core MCV app, and that should be good to go for any Linux and Mac user. In any event, feel free to suggest anything or fork and contribute at your own pace, all invited :).

Cheers!
